{% set name = "compas_robots" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/compas_robots-{{ version }}.tar.gz
  sha256: 84daf63eeea664dc9de5beb5cf944680444ef7c5a8f5605eab5910d735b538fc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - compas >=2.4.3,<3
    - python >=3.6

test:
  imports:
    - compas_robots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/compas-dev/compas_robots
  summary: 'Basic infrastructure for working with robots in COMPAS'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gonzalocasas
