{% set name = "compas_robots" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/compas_robots-{{ version }}.tar.gz
  sha256: 5d5ec8674ad9652a025d9add01e8a03fc13cafd48c2abf2dc9a7a89f110c4e80

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - compas
    - python >=3.6

test:
  imports:
    - compas_robots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gramaziokohler/compas_robots
  summary: 'Basic infrastructure for working with robots in COMPAS'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gonzalocasas
