{% set name = "compas_robots" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/compas_robots-{{ version }}.tar.gz
  sha256: ae2d600cd34f17420fe67cdc5fa7a3dc5bfc1ad5ebf32d6985f550adaed48c58

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - compas >=2.3,<3
    - python >=3.6

test:
  imports:
    - compas_robots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gramaziokohler/compas_robots
  summary: 'Basic infrastructure for working with robots in COMPAS'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gonzalocasas
