{% set name = "compas_robots" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/compas_robots-{{ version }}.tar.gz
  sha256: 2de37049432c01ab89c69e5e2b520ba15e80f71cc08458dcb42a6be6be430324

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - compas
    - python >=3.6

test:
  imports:
    - compas_robots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gramaziokohler/compas_robots
  summary: 'Basic infrastructure for working with robots in COMPAS'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gonzalocasas
